### ISSUE TITLE
Support non-POSIX Windows

### ISSUE THREAD

**Issue by sashka** [sashka/atomicfile#4]

**Comment by sashka** [comment]
I hardly believe it will be implemented.

**Comment by untitaker** [comment]
Please reopen, it's a useful discussion to have nevertheless.

In #5 you mentioned MoveFileTransacted, but this function is discouraged by MS:

>Microsoft strongly recommends developers utilize alternative means to achieve your application’s needs. Many scenarios that TxF was developed for can be achieved through simpler and more readily available techniques. Furthermore, TxF may not be available in future versions of Microsoft Windows.

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365241%28v=vs.85%29.aspx

**Comment by sashka** [comment]
It was a kind of reminder for myself, but I've never needed it for 3 years, and noone else needed it. I hardly believe I will do it myself, but I do believe anyone who needs this feature may open a PR.
