### ISSUE TITLE
no support for self-defined tmpname

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [sashka/atomicfile#8]
kills the utility of this library for writing alternative maildir implementations

**Comment by sashka** [comment]
Pull request will be very appreciated. Thank you.

**Comment by untitaker** [comment]
@sashka I'm also interested in this. Could you reopen this issue?

**Comment by untitaker** [comment]
BTW, yes, I'd write a PR for this.

**Comment by sashka** [comment]
PR will open its own issue.

**Comment by untitaker** [comment]
That's somewhat true, but you still loose the ability to reject an implementation instead of the feature itself. Having a clear separation between issues and PRs helps with that.

**Comment by sashka** [comment]
I'll take this risk in favour of keeping process simple and code-oriented. This particular library is *extremely* focused on a single goal and it's hard to believe we need a process like frameworks like Django or Tornado have.

**Comment by untitaker** [comment]
Let's take this discussion to #9.
