### ISSUE TITLE
Mode for not overwriting existing files

### ISSUE THREAD

**Issue by untitaker** [sashka/atomicfile#9]
I'm looking to replace https://github.com/untitaker/vdirsyncer/blob/master/vdirsyncer/utils/__init__.py#L238 with your library, and apart from https://github.com/sashka/atomicfile/issues/8 I am missing another feature:

I'd like the contextmanager to raise errors when the target file exists. ``rename`` silently overwrites files while a combination of ``link + unlink`` doesn't. I'm definetly willing to write a patch, but I'd like to get confirmation that it would be accepted.

Also, please don't close this issue if you're not willing to implement it yourself, as it prevents discussion.

**Comment by sashka** [comment]
If a PR has tests and tests passed, this PR is accepted in 80% of cases. I can't guarantee this, but I'm an optimist.

**Comment by untitaker** [comment]
Going off-topic here a bit:

I'm not sure how to deal with this, but here goes: As said above, your way of handling issues is suboptimal, I believe. It doesn't allow for a clear distinction between features for which an implementation would be accepted in principle, and issues that are either unfixable or out of scope.

I think you should consider using labels, or issue assignments to further differentiate between issues that *you want to fix*, and things that would be "nice to have".

**Comment by sashka** [comment]
Thank you for your opinion. I've never rejected a PR because of "a principle", only code and backward compatibility matter here.

**Comment by untitaker** [comment]
Huh... so if I would submit my ASCII-art implementation of nyan cat to this library, you would merge it as long as the code is fine? :-P

**Comment by untitaker** [comment]
Maybe that was a childish response, here's a more serious attempt: Suppose I wanted to implement atomic file writes for Windows, and I spend a lot of time with this, adding ~300 lines of code and a C-extension as dependency... would you accept it? If not, wouldn't it be better to discuss this before implementing it?

**Comment by sashka** [comment]
You will use those atomic writes for Windows, aren't you? If you will, it makes no difference for you whether I accept your code of not, you're going to make this library better for your particular use case. 

All offtopic discussion to be wiped out of this issue now. Thank you.

**Comment by untitaker** [comment]
> You will use those atomic writes for Windows, aren't you? If you will, it makes no difference for you whether I accept your code of not, you're going to make this library better for your particular use case. 
> 
> All offtopic discussion to be wiped out of this issue now. Thank you.

...nevermind.
